# Generated by Django 3.1.5 on 2021-01-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproductslist',
            name='product_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='availableproductslist',
            name='product_rating',
            field=models.IntegerField(),
        ),
    ]
